In [1]:
import requests
import lxml
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
all_quotes = []
page = 1
while True:
    url = f'http://quotes.toscrape.com/page/{page}/'
    response = requests.get(url)
    if response.status_code != 200:
        break
    soup = BeautifulSoup(response.text, 'lxml')
    quotes = soup.select('.quote')
    for q in quotes:
        text = q.select_one('.text').text
        author = q.select_one('.author').text
        all_quotes.append({
            'Quote': text,
            'Author': author
        })
    next_button = soup.select_one('li.next')
    if next_button:
        page += 1
    else:
        break
df = pd.DataFrame(all_quotes)
df.head()

                                               Quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [4]:
df

                                                Quote              Author
0   “The world as we have created it is a process ...     Albert Einstein
1   “It is our choices, Harry, that show what we t...        J.K. Rowling
2   “There are only two ways to live your life. On...     Albert Einstein
3   “The person, be it gentleman or lady, who has ...         Jane Austen
4   “Imperfection is beauty, madness is genius and...      Marilyn Monroe
..                                                ...                 ...
95  “You never really understand a person until yo...          Harper Lee
96  “You have to write the book that wants to be w...   Madeleine L'Engle
97  “Never tell the truth to people who are not wo...          Mark Twain
98        “A person's a person, no matter how small.”           Dr. Seuss
99  “... a mind needs books as a sword needs a whe...  George R.R. Martin

[100 rows x 2 columns]

In [20]:
df['Author'].value_counts()

Author
Albert Einstein           10
J.K. Rowling               9
Marilyn Monroe             7
Dr. Seuss                  6
Mark Twain                 6
C.S. Lewis                 5
Jane Austen                5
Bob Marley                 3
Eleanor Roosevelt          2
Charles Bukowski           2
Suzanne Collins            2
George R.R. Martin         2
Ralph Waldo Emerson        2
Mother Teresa              2
Ernest Hemingway           2
J.D. Salinger              1
George Bernard Shaw        1
J.R.R. Tolkien             1
Alfred Tennyson            1
Terry Pratchett            1
John Lennon                1
George Carlin              1
W.C. Fields                1
Ayn Rand                   1
Jimi Hendrix               1
J.M. Barrie                1
E.E. Cummings              1
Khaled Hosseini            1
Harper Lee                 1
Helen Keller               1
Haruki Murakami            1
Stephenie Meyer            1
Garrison Keillor           1
Thomas A. Edison           1
Douglas Adams              1
Elie Wiesel                1
Friedrich Nietzsche        1
André Gide                 1
Allen Saunders             1
Pablo Neruda               1
Jim Henson                 1
Alexandre Dumas fils       1
Charles M. Schulz          1
William Nicholson          1
Jorge Luis Borges          1
George Eliot               1
Martin Luther King Jr.     1
James Baldwin              1
Steve Martin               1
Madeleine L'Engle          1
Name: count, dtype: int64

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

In [ ]:
chrome_options = Options()
chrome_options.add_argument('--headless')
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=chrome_options)
all_quotes = []
page = 1
try:
    while True:
        url = f'https://comic.naver.com/bestChallenge?page={page}'
        driver.get(url)
        time.sleep(1.5)
        quotes = driver.find_elements(By.CLASS_NAME, 'ChallengeListItem__info_area--hnJTz')
        if not quotes:
            break
        for q in quotes:
            try:
                title=q.find_element(By.CLASS_NAME, 'ContentTitle__title--e3qXt').text
                author=q.find_element(By.CLASS_NAME, 'ContentAuthor__author--CTAAP').text
                rating=q.find_element(By.CLASS_NAME, 'Rating__star_area--dFzsb').text.replace('별점', '').strip()
                views=q.find_element(By.CLASS_NAME, 'Rating__view_area--GQb_S').text.replace('조회수', '').strip()

                all_quotes.append({
                    'Title': title,
                    'Author': author,
                    'Rating': rating,
                    'Views': views,
                })
            except:
                continue
        next_btn = driver.find_elements(By.CLASS_NAME, 'PageNavigation__button_next--B9N_1')
        if next_btn:
            is_disabled = next_btn[0].get_attribute('disabled')
            if is_disabled is not None:
                break
        page += 1
except Exception as e:
    print(f"에러 발생: {e}")
finally:
    driver.quit()
    print(f"총 {len(all_quotes)}개의 데이터를 수집했습니다.")
df = pd.DataFrame(all_quotes)
df.to_csv('Webtoon_All.csv', index=False, encoding='utf-8-sig')
df

In [2]:
%pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Collecting selenium
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Collecting certifi>=2026.1.4 (from selenium)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\programdata\anaconda3\lib\site-packages (from selenium) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\programdata\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\programdata\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: h11<1,>=0.16.0 in c:\programdata\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 9.5/9.5 MB 86.6 MB/s  0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, urllib3, outcome, certifi, trio, trio-websocket, selenium

   ----- ---------------------------------- 1/7 [urllib3]
   ----- ---------------------------------- 1/7 [urllib3]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------- ----------------- 4/7 [trio]
   ---------------------------- ----------- 5/7 [trio-websocket]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------- ----- 6/7 [selenium]
   ---------------------------------------- 7/7 [selenium]

Successfully installed certifi-2026.2.25 outcome-1.3.0.post0 selenium-4.41.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.6.3 wsproto-1.3.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
%pip install webdriver-manager

Defaulting to user installation because normal site-packages is not writeable
Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from webdriver-manager) (2.32.5)
Requirement already satisfied: python-dotenv in c:\programdata\anaconda3\lib\site-packages (from webdriver-manager) (1.1.0)
Requirement already satisfied: packaging in c:\users\user\appdata\roaming\python\python313\site-packages (from webdriver-manager) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from requests->webdriver-manager) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\roaming\python\python313\site-packages (from requests->webdriver-manager) (2026.2.25)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Installing collected packages: webdriver-manager
Successfully installed webdriver-manager-4.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import requests
from bs4 import BeautifulSoup
import lxml
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import time

In [15]:
# url = "https://comic.naver.com/webtoon?tab=wed" # 수요일
url = "https://comic.naver.com/webtoon?tab=thu" # 목요일

In [16]:
chrome_options = Options()
chrome_options.add_argument('--headless') # 창 없이 실행하고 싶을 때 주석 해제
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=chrome_options)
driver.get(url)
# time.sleep(2) 한 페이지에서 한번 가져오는 것이기에 필요 없어보임
articles = driver.find_elements(By.CSS_SELECTOR, 'div.ContentList__info_area--bXx7h')
# time.sleep(2)
for i, article in enumerate(articles, 1):
    # 화면에 보이는 텍스트(제목) 가져오기 
    title = article.find_elements(By.CSS_SELECTOR, "span.text")
    # 숨겨진 속성(링크 주소) 가져오기
    author = article.find_element(By.CSS_SELECTOR, "a.ContentAuthor__author--CTAAP").text
    print(f"{i}. 웹툰 제목 : {title[0].text}")
    print(f" 저자 : {author}")
    print(f" 별점 : {title[1].text} \n {'='*80}")
driver.quit()
print("\n수집이 완료되었습니다.")

1. 웹툰 제목 : 만남어플 중독
 저자 : 루즌아
 별점 : 9.57
 ================================================================================
2. 웹툰 제목 : 나노마신
 저자 : 현절무 / 금강불괴 / 한중월야
 별점 : 9.80
 ================================================================================
3. 웹툰 제목 : 마흔 즈음에
 저자 : 서쿤스
 별점 : 9.91
 ================================================================================
4. 웹툰 제목 : 육아일기
 저자 : 자까
 별점 : 9.96
 ================================================================================
5. 웹툰 제목 : 소꿉친구 컴플렉스
 저자 : 은하이
 별점 : 9.83
 ================================================================================
6. 웹툰 제목 : 재벌집 막내아들
 저자 : JP / 김병관 / 산경(山景)
 별점 : 9.97
 ================================================================================
7. 웹툰 제목 : 별 거 아니겠지
 저자 : 쥐망
 별점 : 9.93
 ================================================================================
8. 웹툰 제목 : 천마육성
 저자 : 광휘 / 조형근
 별점 : 9.91
 ================================================================================
9. 웹툰 제목 : 게임 속 바바리안으로 살아남기
 저자 : 팀 더 지크 / MIDNIGHT STUDIO / 정윤강
 별점 : 9.97
 ================================================================================
10. 웹툰 제목 : 무사만리행
 저자 : 운 / 배민기
 별점 : 9.91
 ================================================================================
11. 웹툰 제목 : 풍작이에요, 마왕님!
 저자 : 이현민 / 여강현 / 문백경
 별점 : 9.98
 ================================================================================
12. 웹툰 제목 : 마음의소리(였던 것)
 저자 : 조석
 별점 : 9.93
 ================================================================================
13. 웹툰 제목 : 먹는 인생2
 저자 : 홍끼
 별점 : 9.96
 ================================================================================
14. 웹툰 제목 : 송이연 50살, 이혼 한 달 차
 저자 : 인유유
 별점 : 9.84
 ================================================================================
15. 웹툰 제목 : 작두
 저자 : 232 / POGO
 별점 : 9.95
 ================================================================================
16. 웹툰 제목 : 이세계 캠핑으로 힐링 라이프
 저자 : 일인분 / 맹깐 / 금의행
 별점 : 9.97
 ================================================================================
17. 웹툰 제목 : 오늘의 한요일은 여자다
 저자 : 송극장
 별점 : 9.89
 ================================================================================
18. 웹툰 제목 : 현실퀘스트
 저자 : 이주운 / 태성
 별점 : 9.82
 ================================================================================
19. 웹툰 제목 : 종말에서 살아남기
 저자 : 송
 별점 : 9.86
 ================================================================================
20. 웹툰 제목 : 구세라
 저자 : 승 / 한기쁨
 별점 : 9.83
 ================================================================================
21. 웹툰 제목 : 국정원 말단직원
 저자 : MUTE / 삼둘
 별점 : 9.40
 ================================================================================
22. 웹툰 제목 : 나 혼자 네크로맨서
 저자 : 김경열 / 김동준 / 지점장
 별점 : 9.94
 ================================================================================
23. 웹툰 제목 : 사내연애 사절!
 저자 : 두부 / 남수
 별점 : 9.97
 ================================================================================
24. 웹툰 제목 : 도나츠와 서커스
 저자 : 오븐
 별점 : 9.98
 ================================================================================
25. 웹툰 제목 : 정글쥬스
 저자 : 형은 / 쥬더
 별점 : 9.93
 ================================================================================
26. 웹툰 제목 : 내향남녀
 저자 : 나
 별점 : 9.97
 ================================================================================
27. 웹툰 제목 : 대마법사 커리큘럼
 저자 : 덩배
 별점 : 9.96
 ================================================================================
28. 웹툰 제목 : 회귀한 천재 헌터의 슬기로운 청소생활
 저자 : 고일고일 / 달비트
 별점 : 9.86
 ================================================================================
29. 웹툰 제목 : 당신의 살인을 위하여
 저자 : 세윤 / 징크
 별점 : 9.92
 ================================================================================
30. 웹툰 제목 : 백투더찬비
 저자 : 장사휘
 별점 : 9.61
 ================================================================================
31. 웹툰 제목 : 쿠베라
 저자 : 카레곰
 별점 : 9.96
 ================================================================================
32. 웹툰 제목 : 별정직 공무원
 저자 : 권소라, 서재원 / ch, 말패
 별점 : 9.97
 ================================================================================
33. 웹툰 제목 : 시한부 천재 암흑기사
 저자 : 판테라 / 나기 / 정선율
 별점 : 9.83
 ================================================================================
34. 웹툰 제목 : 폐급연애
 저자 : 멜리, 웬즈데이
 별점 : 8.20
 ================================================================================
35. 웹툰 제목 : 이과장 생존기
 저자 : 맷집왕 / 서윤 / 불량집사
 별점 : 9.88
 ================================================================================
36. 웹툰 제목 : 최강전설 강해효
 저자 : 최병열
 별점 : 9.55
 ================================================================================
37. 웹툰 제목 : 사시미 한 자루로 아카데미를 씹어먹음
 저자 : GMAN / 탕아후루
 별점 : 9.94
 ================================================================================
38. 웹툰 제목 : 쓰레기의 법칙
 저자 : 서연
 별점 : 9.87
 ================================================================================
39. 웹툰 제목 : 김오진과 이상한 동물들
 저자 : 기선 / 필살린
 별점 : 9.97
 ================================================================================
40. 웹툰 제목 : 안녕 오목눈이 그리핀!
 저자 : 임형
 별점 : 9.93
 ================================================================================
41. 웹툰 제목 : 삼이는 재생한다
 저자 : 강은영
 별점 : 9.98
 ================================================================================
42. 웹툰 제목 : 배드 본 블러드
 저자 : 현가 / D-Park / 백수귀족
 별점 : 9.96
 ================================================================================
43. 웹툰 제목 : 언더복서
 저자 : 눈매 / 이재훈
 별점 : 9.47
 ================================================================================
44. 웹툰 제목 : 게임 최강 트롤러
 저자 : 박종석 / YATO / 군만두먹자
 별점 : 9.91
 ================================================================================
45. 웹툰 제목 : 전직용병의 검사생활
 저자 : 박성호 / 양동철 / 10000LAB
 별점 : 9.69
 ================================================================================
46. 웹툰 제목 : 죽여주는 옆집 남자
 저자 : 1호 / bdo
 별점 : 9.75
 ================================================================================
47. 웹툰 제목 : 천재 회사원이 선넘으면 생기는일
 저자 : 오십이 / 도루묵 / 한룡
 별점 : 9.90
 ================================================================================
48. 웹툰 제목 : 종이호랑이
 저자 : 몹시찰진우럭 / 몹시찰진우럭, 영목
 별점 : 9.96
 ================================================================================
49. 웹툰 제목 : 모두가 그녀를 사랑해
 저자 : 스리라챠 / 지민
 별점 : 9.91
 ================================================================================
50. 웹툰 제목 : 최서연의 회피한 날들
 저자 : 김노이
 별점 : 9.77
 ================================================================================
51. 웹툰 제목 : 천만배우의 딸이 되었다
 저자 : 마로
 별점 : 9.81
 ================================================================================
52. 웹툰 제목 : 공작가의 남장 하인이 되었다
 저자 : HBR / 갸우 / 메이비Y
 별점 : 9.94
 ================================================================================
53. 웹툰 제목 : 고고밍밍고
 저자 : 밍밍고
 별점 : 9.92
 ================================================================================
54. 웹툰 제목 : 용사 카리엘
 저자 : 김감준
 별점 : 9.94
 ================================================================================
55. 웹툰 제목 : 복학생
 저자 : 각설이
 별점 : 7.84
 ================================================================================
56. 웹툰 제목 : 신의 요리
 저자 : 차정평 / 레블스튜디오
 별점 : 9.74
 ================================================================================
57. 웹툰 제목 : 마왕까지 한 걸음
 저자 : 윤홍
 별점 : 9.95
 ================================================================================
58. 웹툰 제목 : 저승침공
 저자 : 신선젬 / RAZR
 별점 : 9.82
 ================================================================================
59. 웹툰 제목 : 규격 외 혈통 천재
 저자 : 초멍 / 피콕 / 소울풍
 별점 : 9.61
 ================================================================================
60. 웹툰 제목 : 경계선
 저자 : 파트 / 꿀봉이 / 피숙혜
 별점 : 9.91
 ================================================================================
61. 웹툰 제목 : 소심한 호랭이 코코
 저자 : 키몽
 별점 : 9.98
 ================================================================================
62. 웹툰 제목 : 최강의 로맨티스트
 저자 : 한별
 별점 : 9.65
 ================================================================================
63. 웹툰 제목 : 휴먼 웨어러블
 저자 : 쥬타인
 별점 : 9.85
 ================================================================================
64. 웹툰 제목 : 특급 계약 결혼의 말로
 저자 : 구당 / 꾸왕 / 션킴
 별점 : 9.96
 ================================================================================
65. 웹툰 제목 : 문과X이과
 저자 : 다빈
 별점 : 9.94
 ================================================================================
66. 웹툰 제목 : 지는 쪽이 영부인
 저자 : 최유진 / 강지영
 별점 : 9.85
 ================================================================================
67. 웹툰 제목 : 킬더킹
 저자 : 마사토끼 / joana
 별점 : 9.69
 ================================================================================
68. 웹툰 제목 : 판타지 입소대
 저자 : 서패스 / 먼츠
 별점 : 9.39
 ================================================================================
69. 웹툰 제목 : 소소한 기행
 저자 : 쑈랑
 별점 : 9.90
 ================================================================================
70. 웹툰 제목 : 이세계 싱글대디
 저자 : 왓챠 / W
 별점 : 9.95
 ================================================================================
71. 웹툰 제목 : 독방의 글쓴이
 저자 : 강일
 별점 : 9.91
 ================================================================================
72. 웹툰 제목 : 김 대리는 아이돌이 싫어
 저자 : 김드림 / 플민 / 퇴사연습생
 별점 : 9.95
 ================================================================================
73. 웹툰 제목 : 살아야 죽는 남자
 저자 : 차세기
 별점 : 9.93
 ================================================================================
74. 웹툰 제목 : 컬러리스트
 저자 : 89line
 별점 : 9.90
 ================================================================================
75. 웹툰 제목 : 본능적인 청혼
 저자 : 개굴 / 듀밤 / 김노라
 별점 : 9.62
 ================================================================================
76. 웹툰 제목 : 엄청 소환된 건에 대하여
 저자 : 사이토사 / 츠구토쿠
 별점 : 8.33
 ================================================================================
77. 웹툰 제목 : 마리오네타
 저자 : 미리암 보나스트레
 별점 : 9.97
 ================================================================================
78. 웹툰 제목 : 짐승같은 것들
 저자 : 김태희
 별점 : 9.94
 ================================================================================
79. 웹툰 제목 : 흑역사가 역주행한다
 저자 : 이에프 / 쇼메
 별점 : 9.94
 ================================================================================
80. 웹툰 제목 : 히든클래스 중력자로 최강을 노린다
 저자 : 네코코 / 스나타
 별점 : 8.85
 ================================================================================
81. 웹툰 제목 : 수사9단0
 저자 : 김선권
 별점 : 9.80
 ================================================================================
82. 웹툰 제목 : 미모사
 저자 : 삼중
 별점 : 9.93
 ================================================================================
83. 웹툰 제목 : 염매
 저자 : 갯첨서
 별점 : 9.87
 ================================================================================
84. 웹툰 제목 : 작성자OO
 저자 : 이배 / 반숙
 별점 : 9.62
 ================================================================================
85. 웹툰 제목 : 학생만 하면 안 될까요?
 저자 : 글비 / 나우
 별점 : 9.94
 ================================================================================
86. 웹툰 제목 : 이상한 나라의 솔
 저자 : 루시드
 별점 : 9.98
 ================================================================================
87. 웹툰 제목 : 봉구리 로큰롤
 저자 : 봉구
 별점 : 9.88
 ================================================================================
88. 웹툰 제목 : 어느 날 갑자기 최애가 생겼다
 저자 : 맛스타
 별점 : 9.84
 ================================================================================
89. 웹툰 제목 : 수사중 연애금지!
 저자 : 이재홍
 별점 : 9.75
 ================================================================================
90. 웹툰 제목 : 티라노 노경수
 저자 : 힙합신선
 별점 : 9.95
 ================================================================================
91. 웹툰 제목 : 별의별 지X은
 저자 : 꿀타래 / 모눈
 별점 : 9.75
 ================================================================================
92. 웹툰 제목 : 추억이 찾아오는 가게
 저자 : 꼬모소이
 별점 : 9.97
 ================================================================================
93. 웹툰 제목 : 풀 보이
 저자 : 커북이
 별점 : 9.87
 ================================================================================
94. 웹툰 제목 : 2차전직 스킵용사
 저자 : 김장훈 / 박수봉
 별점 : 9.53
 ================================================================================
95. 웹툰 제목 : 유월의 소한
 저자 : 윤정민
 별점 : 9.21
 ================================================================================
96. 웹툰 제목 : 내 어디가 좋아?
 저자 : 아르몽
 별점 : 9.90
 ================================================================================
97. 웹툰 제목 : 대단한 빈센트
 저자 : 필원 / 호우자
 별점 : 9.87
 ================================================================================
98. 웹툰 제목 : 누가 어른 되면 다 된댔어?
 저자 : 정오
 별점 : 9.85
 ================================================================================
99. 웹툰 제목 : 아이캣치유
 저자 : 코앳 / 우주돌, 코앳
 별점 : 9.93
 ================================================================================
100. 웹툰 제목 : 내가 싫어하는 남자친구
 저자 : 하늘
 별점 : 9.86
 ================================================================================
101. 웹툰 제목 : 최강 매니저
 저자 : 현마담
 별점 : 9.67
 ================================================================================
102. 웹툰 제목 : 기프트
 저자 : 김에그 / 라군
 별점 : 9.58
 ================================================================================
103. 웹툰 제목 : 길티액스
 저자 : 정샛별
 별점 : 9.56
 ================================================================================
104. 웹툰 제목 : 내 여자친구는 이세계 용사?!
 저자 : 사다함
 별점 : 9.49
 ================================================================================
105. 웹툰 제목 : 랭커랑 연애가능
 저자 : CHYA
 별점 : 9.86
 ================================================================================

수집이 완료되었습니다.

In [ ]:
chrome_options = Options()
chrome_options.add_argument('--headless')
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=chrome_options)
all_quotes = []
page = 1
try:
    while True:
        url = f'https://comic.naver.com/bestChallenge?page={page}'
        driver.get(url)
        time.sleep(1.5)
        quotes = driver.find_elements(By.CLASS_NAME, )