In [1]:
import requests
import lxml
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
all_quotes = []
page = 1
while True:
    url = f'http://quotes.toscrape.com/page/{page}/'
    response = requests.get(url)
    if response.status_code != 200:
        break
    soup = BeautifulSoup(response.text, 'lxml')
    quotes = soup.select('.quote')
    for q in quotes:
        text = q.select_one('.text').text
        author = q.select_one('.author').text
        all_quotes.append({
            'Quote': text,
            'Author': author
        })
    next_button = soup.select_one('li.next')
    if next_button:
        page += 1
    else:
        break
df = pd.DataFrame(all_quotes)
df.head()

                                               Quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [4]:
df

                                                Quote              Author
0   “The world as we have created it is a process ...     Albert Einstein
1   “It is our choices, Harry, that show what we t...        J.K. Rowling
2   “There are only two ways to live your life. On...     Albert Einstein
3   “The person, be it gentleman or lady, who has ...         Jane Austen
4   “Imperfection is beauty, madness is genius and...      Marilyn Monroe
..                                                ...                 ...
95  “You never really understand a person until yo...          Harper Lee
96  “You have to write the book that wants to be w...   Madeleine L'Engle
97  “Never tell the truth to people who are not wo...          Mark Twain
98        “A person's a person, no matter how small.”           Dr. Seuss
99  “... a mind needs books as a sword needs a whe...  George R.R. Martin

[100 rows x 2 columns]

In [20]:
df['Author'].value_counts()

Author
Albert Einstein           10
J.K. Rowling               9
Marilyn Monroe             7
Dr. Seuss                  6
Mark Twain                 6
C.S. Lewis                 5
Jane Austen                5
Bob Marley                 3
Eleanor Roosevelt          2
Charles Bukowski           2
Suzanne Collins            2
George R.R. Martin         2
Ralph Waldo Emerson        2
Mother Teresa              2
Ernest Hemingway           2
J.D. Salinger              1
George Bernard Shaw        1
J.R.R. Tolkien             1
Alfred Tennyson            1
Terry Pratchett            1
John Lennon                1
George Carlin              1
W.C. Fields                1
Ayn Rand                   1
Jimi Hendrix               1
J.M. Barrie                1
E.E. Cummings              1
Khaled Hosseini            1
Harper Lee                 1
Helen Keller               1
Haruki Murakami            1
Stephenie Meyer            1
Garrison Keillor           1
Thomas A. Edison           1
Douglas Adams              1
Elie Wiesel                1
Friedrich Nietzsche        1
André Gide                 1
Allen Saunders             1
Pablo Neruda               1
Jim Henson                 1
Alexandre Dumas fils       1
Charles M. Schulz          1
William Nicholson          1
Jorge Luis Borges          1
George Eliot               1
Martin Luther King Jr.     1
James Baldwin              1
Steve Martin               1
Madeleine L'Engle          1
Name: count, dtype: int64